baseURL = "https://kims-blog.netlify.com/"
languageCode = "en-us"
title = "Kim's Blog"
theme = "rusty"

[params]
    github_username = "KimLizCass"
    description = "Adventures of a female programmer"
